// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:2169da72-e60b-4649-9da8-7307a59b147c",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_vVQK1pOgI",
    "aws_user_pools_web_client_id": "5pgg911ghajnatq2lit3islbha",
    "oauth": {}
};


export default awsmobile;
